class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """
        t is generated by shuffling s
        add one letter at random position
        
        it could be the count of the letter that diffs
        """
        s_dict = collections.Counter(s)
        t_dict = collections.Counter(t)

        for letter in t:
            if t_dict[letter] != s_dict[letter]:
                return letter
        