#!/bin/python3

import math
import os
import random
import re
import sys

def gradingStudents(grades):
    ans = []
    for val in grades:
        if val < 38:
                ans.append(val)
        elif val >= 38:
            if ((((val//5) + 1)*5) - val) < 3:
                    ans.append((((val//5) + 1)*5))
            else:
                    ans.append(val)
    return ans
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
